- name: Install K3s control plane
  hosts: k3s_control_plane
  become: true

  tasks:
    - name: Install K3s server
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure K3s service is running
      systemd:
        name: k3s
        state: started
        enabled: true

    - name: Retrieve K3s node token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Display K3s token
      debug:
        var: k3s_token.stdout